package cn.djzhao.model.mapper;

import cn.djzhao.model.entity.Exam;
import cn.djzhao.model.entity.ExamQuery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface ExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Exam
     *
     * @mbg.generated
     */
    long countByExample(ExamQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Exam
     *
     * @mbg.generated
     */
    int deleteByExample(ExamQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    @Delete({
        "delete from exam",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    @Insert({
        "insert into exam (class_name, class_number, ",
        "day_limit, statu, ",
        "mark)",
        "values (#{className,jdbcType=VARCHAR}, #{classNumber,jdbcType=VARCHAR}, ",
        "#{dayLimit,jdbcType=INTEGER}, #{statu,jdbcType=INTEGER}, ",
        "#{mark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int insertSelective(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    List<Exam> selectByExampleWithRowbounds(ExamQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Exam selectOneByExample(ExamQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    List<Exam> selectByExample(ExamQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, class_name, class_number, day_limit, statu, mark",
        "from exam",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("cn.djzhao.model.mapper.ExamMapper.BaseResultMap")
    Exam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Exam record, @Param("example") ExamQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Exam record, @Param("example") ExamQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    @Update({
        "update exam",
        "set class_name = #{className,jdbcType=VARCHAR},",
          "class_number = #{classNumber,jdbcType=VARCHAR},",
          "day_limit = #{dayLimit,jdbcType=INTEGER},",
          "statu = #{statu,jdbcType=INTEGER},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int insertOrUpdate(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int insertOrUpdateSelective(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Exam> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Exam> list, @Param("selective") Exam.Column... selective);
}