package cn.djzhao.model.mapper;

import cn.djzhao.model.entity.Grade;
import cn.djzhao.model.entity.GradeQuery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Grade
     *
     * @mbg.generated
     */
    long countByGradeple(GradeQuery Gradeple);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Grade
     *
     * @mbg.generated
     */
    int deleteByGradeple(GradeQuery Gradeple);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    @Delete({
        "delete from grade",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    @Insert({
        "insert into grade (class_name, class_number, ",
        "day_limit, statu, ",
        "mark)",
        "values (#{className,jdbcType=VARCHAR}, #{classNumber,jdbcType=VARCHAR}, ",
        "#{dayLimit,jdbcType=INTEGER}, #{statu,jdbcType=INTEGER}, ",
        "#{mark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    List<Grade> selectByGradepleWithRowbounds(GradeQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Grade selectOneByGradeple(GradeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    List<Grade> selectByGradeple(GradeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, class_name, class_number, day_limit, statu, mark",
        "from grade",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("cn.djzhao.model.mapper.GradeMapper.BaseResultMap")
    Grade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int updateByGradepleSelective(@Param("record") Grade record, @Param("example") GradeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int updateByGradeple(@Param("record") Grade record, @Param("example") GradeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    @Update({
        "update grade",
        "set class_name = #{className,jdbcType=VARCHAR},",
          "class_number = #{classNumber,jdbcType=VARCHAR},",
          "day_limit = #{dayLimit,jdbcType=INTEGER},",
          "statu = #{statu,jdbcType=INTEGER},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int insertOrUpdate(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     */
    int insertOrUpdateSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Grade> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Grade> list, @Param("selective") Grade.Column... selective);
}