package cn.djzhao.model.mapper;

import cn.djzhao.model.entity.TermRoom;
import cn.djzhao.model.entity.TermRoomQuery;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface TermRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    long countByExample(TermRoomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    int deleteByExample(TermRoomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    @Delete({
        "delete from term_room",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    @Insert({
        "insert into term_room (room_name, room_space, ",
        "room_layer, room_sign, ",
        "statu, mark)",
        "values (#{roomName,jdbcType=VARCHAR}, #{roomSpace,jdbcType=INTEGER}, ",
        "#{roomLayer,jdbcType=INTEGER}, #{roomSign,jdbcType=INTEGER}, ",
        "#{statu,jdbcType=INTEGER}, #{mark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TermRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    int insertSelective(TermRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    List<TermRoom> selectByExampleWithRowbounds(TermRoomQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TermRoom selectOneByExample(TermRoomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    List<TermRoom> selectByExample(TermRoomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, room_name, room_space, room_layer, room_sign, statu, mark",
        "from term_room",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("cn.djzhao.model.mapper.TermRoomMapper.BaseResultMap")
    TermRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TermRoom record, @Param("example") TermRoomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TermRoom record, @Param("example") TermRoomQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TermRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    @Update({
        "update term_room",
        "set room_name = #{roomName,jdbcType=VARCHAR},",
          "room_space = #{roomSpace,jdbcType=INTEGER},",
          "room_layer = #{roomLayer,jdbcType=INTEGER},",
          "room_sign = #{roomSign,jdbcType=INTEGER},",
          "statu = #{statu,jdbcType=INTEGER},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TermRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    int insertOrUpdate(TermRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     */
    int insertOrUpdateSelective(TermRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TermRoom> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TermRoom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TermRoom> list, @Param("selective") TermRoom.Column... selective);
}